In [12]:
import numpy as np
import pandas as pd
from keras.models import Sequential
from keras.layers import Dense, Dropout, Activation
from keras.optimizers import SGD
train = pd.read_csv('train.csv')
test  = pd.read_csv('test.csv')

print(train.shape)

train_features = train.iloc[:,:561].as_matrix()
test_features = test.iloc[:,:561].as_matrix()

train_results = train.iloc[:,562:].as_matrix()
test_results = test.iloc[:,562:].as_matrix()
train_results_activity=np.zeros((len(train_results),6))
test_results_activity=np.zeros((len(test_results),6))
print(train_resultss)
for k in range (0,len(train_results)):
    if train_results[k] =='STANDING':
        train_results_activity[k][0]=1
    elif train_results[k] =='WALKING':
        train_results_activity[k][1]=1
    elif train_results[k] =='WALKING_UPSTAIRS':
        train_results_activity[k][2]=1
    elif train_results[k] =='WALKING_DOWNSTAIRS':
        train_results_activity[k][3]=1
    elif train_results[k] =='SITTING':
        train_results_activity[k][4]=1
    else:
        train_results_activity[k][5]=1

for k in range (0,len(test_results)):
    if test_results[k] =='STANDING':
        test_results_activity[k][0]=1
    elif test_results[k] =='WALKING':
        test_results_activity[k][1]=1
    elif test_results[k] =='WALKING_UPSTAIRS':
        test_results_activity[k][2]=1
    elif test_results[k] =='WALKING_DOWNSTAIRS':
        test_results_activity[k][3]=1
    elif test_results[k] =='SITTING':
        test_results_activity[k][4]=1
    else:
        test_results_activity[k][5]=1


model = Sequential()
model.add(Dense(64, activation='relu', input_dim=561))
model.add(Dropout(0.5))
model.add(Dense(64, activation='relu'))
model.add(Dropout(0.5))
model.add(Dense(6, activation='softmax'))

sgd = SGD(lr=0.01, decay=1e-6, momentum=0.9, nesterov=True)
model.compile(loss='categorical_crossentropy',
              optimizer=sgd,
              metrics=['accuracy'])

model.fit(train_features, train_resultss,epochs=30,batch_size=128)
score = model.evaluate(test_features, test_resultss, batch_size=128)
print(score)

(999, 563)
[[1. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0.]
 ...
 [1. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0.]]


C:\Users\alshanka.ORADEV\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:11: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  # This is added back by InteractiveShellApp.init_path()
C:\Users\alshanka.ORADEV\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:12: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  if sys.path[0] == '':
C:\Users\alshanka.ORADEV\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:14: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  
C:\Users\alshanka.ORADEV\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:15: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  from ipykernel import kernelapp as app


Epoch 1/30
999/999 [==============================] - 1s 864us/step - loss: 2.0249 - acc: 0.1832
Epoch 2/30
999/999 [==============================] - 0s 53us/step - loss: 1.6163 - acc: 0.3053
Epoch 3/30
999/999 [==============================] - 0s 57us/step - loss: 1.4636 - acc: 0.3744
Epoch 4/30
999/999 [==============================] - 0s 60us/step - loss: 1.3633 - acc: 0.4124
Epoch 5/30
999/999 [==============================] - 0s 74us/step - loss: 1.2272 - acc: 0.4635
Epoch 6/30
999/999 [==============================] - 0s 56us/step - loss: 1.1453 - acc: 0.4935
Epoch 7/30
999/999 [==============================] - 0s 50us/step - loss: 1.0889 - acc: 0.5255
Epoch 8/30
999/999 [==============================] - 0s 60us/step - loss: 1.0206 - acc: 0.5415
Epoch 9/30
999/999 [==============================] - 0s 86us/step - loss: 0.9428 - acc: 0.6056
Epoch 10/30
999/999 [==============================] - 0s 84us/step - loss: 0.8980 - acc: 0.6116
Epoch 11/30
999/999 [=================